//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Health.Fhir.Ingest.Host {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Health.Fhir.Ingest.Host.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;templateType&quot;: &quot;CollectionContent&quot;,
        ///  &quot;template&quot;: [
        ///    {
        ///      &quot;templateType&quot;: &quot;JsonPathContent&quot;,
        ///      &quot;template&quot;: {
        ///        &quot;typeName&quot;: &quot;heartrate&quot;,
        ///        &quot;typeMatchExpression&quot;: &quot;$..[?(@heartrate)]&quot;,
        ///        &quot;deviceIdExpression&quot;: &quot;$.deviceid&quot;,
        ///		&quot;patientIdExpression&quot;: &quot;$.patientid&quot;,
        ///        &quot;timestampExpression&quot;: &quot;$.measurementdatetime&quot;,
        ///        &quot;values&quot;: [
        ///          {
        ///            &quot;required&quot;: &quot;true&quot;,
        ///            &quot;valueExpression&quot;: &quot;$.heartrate&quot;,
        ///            &quot;valueName&quot;: &quot;hr&quot;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceContent {
            get {
                return ResourceManager.GetString("DeviceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;templateType&quot;: &quot;CollectionFhir&quot;,
        ///  &quot;template&quot;: [
        ///    {
        ///      &quot;templateType&quot;: &quot;CodeValueFhir&quot;,
        ///      &quot;template&quot;: {
        ///        &quot;codes&quot;: [
        ///          {
        ///            &quot;code&quot;: &quot;8867-4&quot;,
        ///            &quot;system&quot;: &quot;http://loinc.org&quot;,
        ///            &quot;display&quot;: &quot;Heart rate&quot;
        ///          }
        ///        ],
        ///        &quot;periodInterval&quot;: 60,
        ///        &quot;typeName&quot;: &quot;heartrate&quot;,
        ///        &quot;value&quot;: {
        ///          &quot;defaultPeriod&quot;: 1000,
        ///          &quot;unit&quot;: &quot;count/min&quot;,
        ///          &quot;valueName&quot;: &quot;hr&quot;,
        ///          &quot;valueType&quot;: &quot;SampledData&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FhirMapping {
            get {
                return ResourceManager.GetString("FhirMapping", resourceCulture);
            }
        }
    }
}
